;/* Version a5a0761b5eea61f134b60a8494149e56 v:4.5.10.2468, c:c2e5dcf029cd39317e176e1850e97c537c8a43e6, b:4.5.10.2468 */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var k=window.ADRUM;if(k&&k.q&&!0!==window["adrum-disable"]){var A=window.console,y=A&&"function"==typeof A.log?A:{log:function(){}},u=this&&this.lc||function(){var d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])};return function(g,a){function b(){this.constructor=g}d(g,a);g.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}();(function(d){(function(g){g.Ba=function(a){function b(d){return d.replace(/\s/g,
"")===e}var l={a:[1,2,3,"str"]},e='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&g.isFunction(JSON.stringify)&&b(JSON.stringify(l)))return JSON.stringify(a);if("undefined"!==typeof Object&&Object&&g.isFunction(Object.toJSON)&&b(Object.toJSON(l)))return Object.toJSON(a);d.error("M192");return null};g.Ac=function(a,b,l){var e=a,c=l;"xhr"===l&&(e=document.createElement("div"),a.appendChild(e),c="xhr_"+a.getElementsByTagName("div").length);a=document.createElement("p");a.innerHTML="Script loaded from "+
d.conf.adrumExtUrl+". Metrics collected are:";e.appendChild(a);a=document.createElement("table");a.id="ADRUM_"+c;var c=document.createElement("tbody"),h;for(h in b){l=document.createElement("tr");var g=document.createElement("td");g.innerHTML=h;g.className="name";var m=document.createElement("td");m.innerHTML=String(b[h]);m.className="value";l.appendChild(g);l.appendChild(m);c.appendChild(l)}a.appendChild(c);e.appendChild(a)};g.dumpObject=function(){function d(b,l){try{if("object"!=typeof b)return String(b);
if(0<=g.Ab(l,b))return"Already visited";l.push(b);var e;if(g.isArray(b)){for(var c="[ ",h=0;h<b.length;h++)0!=h&&(c+=", "),c+=d(b[h],l);e=c+" ]"}else{var c="{ ",h=!0,f;for(f in b)h?h=!1:c+=", ",c+=d(f,l)+" => "+d(b[f],l);e=c+" }"}return e}catch(m){return"dumpObject failed: "+m}}return function(b){return d(b,[])}}();g.Ab=g.isFunction(Array.prototype.indexOf)?function(d,b){return d.indexOf(b)}:function(d,b){for(var l=0;l<d.length;l++)if(d[l]==b)return l;return-1};g.compareWindows=function(d,b){return d==
b};g.Kc=function(d,b,l,e,c){if(!g.isDefined(b))return b;if(g.isArray(b)){d=[];for(var h=0,f=b.length;h<f;h++)d[h]=g.Kc(h,b[h],l,e,c);return d}if(g.isFunction(b))return b;if(g.isObject(b)){d={};for(h in b)g.hasOwnPropertyDefined(b,h)&&(d[l(h)]=c&&c(h)?b[h]:g.Kc(h,b[h],l,e,c));return d}return e(d,b)};g.dl=function(d){var b=[],l;for(l in d)g.hasOwnPropertyDefined(d,l)&&b.push([l,d[l]]);return b};g.pm=function(){try{localStorage.setItem("try","try");var d=localStorage.getItem("try");localStorage.removeItem("try");
return"try"===d}catch(b){return!1}};g.om=function(){try{var d=g.Ba({v:1});return 1===JSON.parse(d).v}catch(b){return!1}};g.qm=function(){return g.isFunction(window.postMessage)};g.Xi=function(d,b){var l=document.createElement("div");l.innerHTML='<iframe id="'+b+'" src='+d+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(l);return document.getElementById(b)};g.pg=function(d,b){g.isDefined(b)&&(d.parentPageName=b)};g.Sc=function(d){return g.isNumber(d)&&
isFinite(d)&&Math.floor(d)===d};g.Be=function(g){d.log(g);y.log(g)}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(d){d.Ag=function(d){return/^[0-9]+$/.test(d)?Number(d):null};d.mf=function(d){return"number"===typeof d&&!isNaN(d)&&isFinite(d)}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(g){function a(c){var e=c.split("\r\n"),l=/^\s*ADRUM_(\d+): (.+)\s*$/i;c=[];for(var b=0;b<e.length;b++){var g=e[b];try{var a=l.exec(g);a&&c.push([Number(a[1]),a[2]])}catch(k){d.exception(k,
"M195",g)}}Array.prototype.sort.call(c,function(d,c){return d[0]-c[0]});a=[];for(e=0;e<c.length;e++)a.push(c[e][1]);return a}var b=d.utils.hasOwnPropertyDefined,l=null,e=null;g.Ze=function(){e||(e=g.Hf(g.dd(g.cookieMetadataChunks),g.dd(d.footerMetadataChunks)));return e};g.getPageGUID=function(){var c=d.monitor.DOMEventsMonitor,e=d.utils.isObject(c.currentBasePage)&&d.utils.isFunction(c.currentBasePage.guid);if(!l){var b=g.Ze();l=b&&b.clientRequestGUID||(e?c.currentBasePage.guid():d.utils.generateGUID())}return l};
g.Vj=function(c){c=a(c);d.log("M193",c);return g.Hf(g.dd(c))};g.Hf=function(c,e){function l(c){for(var e=0;e<c.length;e++){var h=c[e];h!=b&&0>d.utils.Ab(t,h)&&t.push(h)}}if(!c||0>=c.Ea.length)return null;e||(e=c);var b;if(0<e.Ea.length){if(b=e.Ea[0],0>d.utils.Ab(c.Ea,b))return null}else return d.error("M194"),null;var a=e.serverSnapshotType||c.serverSnapshotType,k=e.hasEntryPointErrors||c.hasEntryPointErrors,t=[];l(c.Ea);l(e.Ea);var n={clientRequestGUID:b,btGlobalAccountName:c.btGlobalAccountName};
0<t.length&&(n.otherClientRequestGUIDs=t);0<g.Gf(c.btTime,e.btTime).length&&(n.btTime=g.Gf(c.btTime,e.btTime));null!==a&&(n.serverSnapshotType=a);null!==k&&(n.hasEntryPointErrors=k);return n};g.Gf=function(d,e){for(var l=d.concat(e),g={},a={},k=0;k<l.length;k++){var t=l[k];t.id in g||(g[t.id]=-1);g[t.id]=Math.max(g[t.id],t.duration);t.id in a||(a[t.id]=-1);a[t.id]=Math.max(a[t.id],t.ert)}var l=[],n;for(n in g)b(g,n)&&l.push({id:n,duration:g[n],ert:a[n]});return l};g.dd=function(c){if(!d.utils.isArray(c))return null;
for(var e=[],l=null,b=[],g=null,a=null,k=0;k<c.length;k++){var n=c[k];if("string"!==typeof n)return null;n=n.replace(/^"|"$/g,"");n=decodeURIComponent(n).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===n.length){var r=n[1];switch(n[0]){case "clientRequestGUID":case "g":e.push(r);break;case "btId":case "i":b.push({id:r,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;n=d.utils.Ag(r);if(!d.utils.mf(n)||-1>n)return null;b[b.length-1].duration=n;break;case "btERT":case "e":if(0===
b.length)return null;n=d.utils.Ag(r);if(!d.utils.mf(n)||-1>n)return null;b[b.length-1].ert=n;break;case "serverSnapshotType":case "s":g=r;break;case "globalAccountName":case "n":l=r;break;case "hasEntryPointErrors":case "h":a=r}}}return 0===e.length?null:{Ea:e,btGlobalAccountName:l,btTime:b,serverSnapshotType:g,hasEntryPointErrors:a}};g.On=a})(d.correlation||(d.correlation={}))})(k||(k={}));(function(d){var g=d.conf||(d.conf={});g.bn=3E3;g.useDebugBeaconParams=d.isDebug;g.mi=1E3;g.Jh=2;g.Ih=5;g.Ch=
5;g.Dh=20;g.Zd=5E3;g.Qa=512;g.hh=10;g.gh=64;g.Uh=10;g.Th=10;g.Ph=300;g.Mh=2048;g.Ra=2048;g.Sa=760;g.zf={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",
userDataBoolean:"udb",userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",
parentPageName:"an",geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(k||(k={}));(function(d){d=d.beacons||(d.beacons={});d.numBeaconsSent=0;d.beaconsSent=[]})(k||(k={}));(function(d){(function(g){var a=function(){function b(){}b.prototype.send=function(l,e){var c=(e?d.conf.beaconUrlHttps:d.conf.beaconUrlHttp)+d.conf.corsEndpointPath+"/"+d.conf.appKey+"/adrum",b;d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrOpen)?(b=new d.xhrConstructor,
d.xhrOpen.call(b,"POST",c)):(b=new XMLHttpRequest,b.open("POST",c));b.setRequestHeader("Content-type","text/plain");var a=d.utils.Ba(l);null!=a&&(d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrSend)?d.xhrSend.call(b,a):b.send(a),d.log("M196",c),d.log("\n"),d.log("<hr/>"),d.isDebug&&g.beaconsSent.push(l),g.numBeaconsSent+=1)};return b}();g.ah=a})(d.beacons||(d.beacons={}))})(k||(k={}));k||(k={});(function(d){var g=function(){function g(d,l,e){this.Ib=d;this.lk=l;this.wd=e}g.prototype.Ic=
function(){try{return g.Ue(this.lk.ADRUM)}catch(b){return d.error("M197"),g.Ue(d)}};g.Ue=function(d){return d.correlation.getPageGUID()};return g}();d.Xg=g})(k||(k={}));(function(d){d.beacons||(d.beacons={})})(k||(k={}));(function(d){(function(d){var a=function(){function b(){this.Cb=[];this.Bc={}}b.prototype.Eb=function(l){if(!l)return"";if(d.hasOwnPropertyDefined(this.Bc,l))return this.Bc[l];var e=this.Cb.length;this.Bc[l]=e;this.Cb[e]=l;return e};return b}();d.Yd=a})(d.utils||(d.utils={}))})(k||
(k={}));(function(d){(function(g){var a=d.utils.map,b=function(){function d(){}d.km=function(d){d=(d||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var c={};d[1]&&(c.protocol=d[1].substring(0,d[1].length-3));d[2]&&(c.path=d[2]);d[3]&&(c.Jl=d[3]);d[4]&&(c.anchor=d[4]);return c};d.kj=function(e,c){var b=d.km(e),g="";b.protocol&&(g+=c.Eb(b.protocol),g+="://");b.path&&(g+=a(b.path.split("/"),c.Eb,c).join("/"));return g+=a([b.Jl,b.anchor],function(d){return d?d[0]+c.Eb(d.slice(1)):""},c).join("")};
d.ij=function(d,c){return""+c.Eb(d)};return d}();g.Kd=b})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(g){(function(g){function b(){var c=null,l=null;try{c=localStorage[e]}catch(b){}if(c)try{c=l=JSON.parse(c),d.utils.isObject(c)&&d.utils.isNumber(c[f])&&-1<c[f]?k=l:d.error("M198")}catch(g){d.exception(g,"M199");try{delete localStorage[e]}catch(h){d.exception(h,"M200")}}}function l(){try{var l=d.channel,b=k[c]||k[h],g=l&&l.V&&l.V.T&&l.V.T.id||(d.utils.isString(b)?b:d.utils.generateGUID());
k[c]=k[h]=g;localStorage[e]=d.utils.Ba(k)}catch(a){}}var e="ADRUM_CLIENTINFO",c="agentId",h="clientId",f="seqId",k;b();k||(k={seqId:0});l();g.Fj=function(){b();var d=k[f]++;l();return d}})(g.ye||(g.ye={}))})(d.og||(d.og={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(){this.urlCapture={filterURLQuery:!1};this.$f=/;jsessionid=[^/?]+/;g.mergeJSON(this.urlCapture,d.conf.userConf.urlCapture);g.isBoolean(this.urlCapture.filterURLQuery)||g.isArray(this.urlCapture.filterURLQuery)||
(d.log("M201"),this.urlCapture.filterURLQuery=!1)}b.im=function(d){for(var e=0,c=0;c<d.length;c++)e=(e<<5)-e+d.charCodeAt(c),e|=0;return e};b.prototype.Pj=function(d){var e="",c,b;if(!g.isString(d))return"";c=d.indexOf("?")+1;0<c&&(b=d.indexOf("#"),0>b?e=d.substring(c):c<=b&&(e=d.substring(c,b)));return e};b.prototype.pj=function(d){var e="",c=this.urlCapture.filterURLQuery,b={},a=0,k,p,q;if(!g.isString(d)||""===d)return"";if(!1===c)return d;k=this.Pj(d);if(""===k)return d;if(g.isArray(c)){for(q=
0;q<c.length;q++)b[c[q]]=!0;c=k+"&";for(q=0;q<c.length;q++)switch(c[q]){case "=":p=c.substring(a,q);break;case "&":case ";":p=p||c.substring(a,q),q++,b[p]||(e+=c.substring(a,q)),a=q,p=null}e=e.substring(0,e.length-1)}""==e&&(k="?"+k);return d.replace(k,e)};b.prototype.na=function(d){if(null===d||void 0===d)return null;if(""===d)return"";var e=d.match(this.$f),c=d;if(null!=e){var b=d.indexOf("?");if(0>b||b>e.index)c=d.replace(this.$f,"")}return c=this.pj(c)};b.prototype.Ie=function(d){if(null===d||
void 0===d)return null;var e=d.indexOf("?"),c=d.indexOf("#");0>e&&(e=Number.MAX_VALUE);0>c&&(c=Number.MAX_VALUE);return d.substring(0,Math.min(e,c))};b.prototype.ol=function(d){if(null===d||void 0===d)return null;var e=this.Ie(d);return e+"?"+b.im(d.substring(e.length))};return b}();g.fn=a;g.W=new a})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(g){(function(g){var b=function(){function b(e,c,l){var g=this;this.Ol=0;this.hd=[];this.af=!1;this.bk=l;d.utils.addEventListener(window,"message",
function(d){g.sl(d)});this.ak=d.utils.Xi(c,e)}b.prototype.sl=function(e){var c;try{if(c=JSON.parse(e.data),"ADRUM_XD"!==c.name)d.log("M202");else if(!0===c.success)if(-1===c.id&&"iframe-ready"===c.data)this.af=!0,this.bk();else{if(this.hd[c.id])this.hd[c.id](c.data)}else d.error("M203",e.data)}catch(b){d.log("M204",b)}};b.prototype.send=function(e,c,b,l){if(this.af){var g=this.Ol++;this.hd[g]=l;this.ak.contentWindow.postMessage(d.utils.Ba({id:g,action:e,key:c,value:b}),"*")}};b.prototype.generateGUID=
function(d,c){this.send("generateGUID",d,null,c)};return b}();g.dh=b})(g.zg||(g.zg={}))})(d.Pg||(d.Pg={}))})(k||(k={}));(function(d){(function(g){var a=function(){function e(){this.qe=new b(e.Tg);this.Og=new b(e.Vg);this.Sm=new l(e.Ug)}e.prototype.init=function(c){this.channel=c;d.utils.pm()&&d.utils.om()?d.utils.qm()&&e.Xk()?this.Am():this.Ig():e.If=!0};e.prototype.Ig=function(){var c=this.qe.load();e.Vk(c)||(c={ver:d.conf.agentVer,id:d.utils.generateGUID()},this.qe.save(c));e.T=c};e.prototype.Am=
function(){var c=this,b=this.Og.load();e.Wk(b)?e.T=b:(d.log("M205"),this.Sm.load(function(b){e.rf(b)?(b={ver:d.conf.agentVer,id:b,ttl:(new Date).getTime()+e.ih},c.Og.save(b),e.T=b,d.log("M206")):d.log("M207")}),d.utils.tryPeriodically(e.qc,function(){return c.isReady()},function(){return c.onReady()},function(){return c.$c()}))};e.Xk=function(){return d.conf.userConf&&d.conf.userConf.xd&&d.conf.userConf.xd.enable};e.Vk=function(d){return d&&d.id&&0<d.id.length};e.Wk=function(d){return d&&e.rf(d.id)&&
d.ttl>(new Date).getTime()};e.rf=function(c){return d.utils.isString(c)&&0<c.length&&0===c.indexOf("XD_")};e.prototype.isReady=function(){return e.If||d.utils.isDefined(e.T)};e.prototype.onReady=function(){this.channel.onResolverReady()};e.prototype.$c=function(){d.log("M208");this.Ig();this.channel.onResolverReady()};e.qc=function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return e}();a.Tg="ADRUM_AGENT_INFO";a.Vg="ADRUM_XD_AGENT_INFO";a.Ug="ADRUM_XD_AGENT_ID";a.ih=6048E5;a.If=!1;g.V=a;var b=function(){function e(d){this.pe=
d}e.prototype.load=function(){var c=null;try{var e=localStorage.getItem(this.pe);e&&(c=JSON.parse(e))}catch(b){d.exception(b,"M209")}return c};e.prototype.save=function(c){try{var e=d.utils.Ba(c);e&&localStorage.setItem(this.pe,e)}catch(b){d.exception(b,"M210")}};return e}(),l=function(){function e(d){this.zi=d}e.prototype.load=function(c){var e=this;try{var b=new d.Pg.zg.dh("cross-domain-store-server-iframe",d.conf.adrumXdUrl,function(){b.generateGUID(e.zi,c)})}catch(l){d.exception(l,"M211")}};return e}()})(d.channel||
(d.channel={}))})(k||(k={}));(function(d){(function(g){var a=d.utils.isString,b=d.utils.isNumber,l=function(){function e(){}e.prototype.Nb=function(c,b,l){c={ver:d.conf.agentVer,dataType:"R",rootGUID:l.Ic(),events:c};d.channel.V.T&&d.channel.V.T.id&&(c.agentId=d.channel.V.T.id);b&&(c.geo=b);return e.Bl(c)};e.Bl=function(c){d.isDebug||(c=e.Qi(c));return c};e.Qi=function(c){var l=new d.utils.Yd,f=new d.utils.Yd;c=d.utils.Kc(null,c,e.Jc,function(c,k){if(!a(k))return k;if(e.Uk(c)){var q=e.Mk(c)&&b(d.conf.userConf.maxUrlLength)?
d.conf.userConf.maxUrlLength:d.conf.Qa;k=e.sd(k,q);k=g.Kd.kj(k,l)}else k=e.Lk(c)?e.sd(k,d.conf.Sa):e.sd(k,d.conf.Mh);e.Ck(c)&&(k=g.Kd.ij(k,f));return k},e.gl);c[e.Jc("guids")]=f.Cb;c[e.Jc("urlParts")]=l.Cb;return c};e.Uk=function(d){return"eventUrl"==d||"parentUrl"==d||"pageReferrer"==d||"pageUrl"==d||"u"==d};e.Ck=function(d){return"eventGUID"==d||"parentGUID"==d||"rootGUID"==d||"clientRequestGUID"==d};e.Lk=function(d){return"userPageName"==d};e.sd=function(d,e){return d.length>e?d.substr(0,e-3)+
"...":d};e.Mk=function(d){return"eventUrl"==d||"parentUrl"==d||"pageReferrer"==d};e.Jc=function(c){if(d.conf.useDebugBeaconParams)return c;var e=d.conf.zf[c];return"undefined"===typeof e?c:e};e.gl=function(d){d=""+d;return 0===d.indexOf("userData")||"parameter"===d};return e}();g.$g=l})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(){}b.prototype.send=function(d,e){for(var c=0;c<d.length;c++)this.Zl(d[c],e)};b.prototype.Zl=function(b,e){var c=(e?d.conf.beaconUrlHttps:
d.conf.beaconUrlHttp)+d.conf.imageEndpointPath,a=document.createElement("img");a.I=!0;try{a.src=c+b}catch(k){}d.isDebug&&g.beaconsSent.push(b);g.numBeaconsSent+=1};return b}();g.yh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){d.ob=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,b-3)+"...");return d};d.Eg=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,(b-3)/2)+"..."+d.substring(d.length-(b-3)/2,d.length));return d};d.wm=function(a,b){a.length<=
b||(a=d.ob(a,b-1),a+=":");return a};d.um=function(a,b,l,e,c,h){a=d.wm(a,e);l=d.ob(l,c);a.length+b.length+l.length>h-3&&(b=d.ob(b,h-3-a.length-l.length));return 0<l.length?a+"//"+b+":"+l:a+"//"+b};d.vm=function(a,b,l){a=d.map(a,function(e){return d.Eg(e,b)});if(a.length>l){var e=a[0];a=a.slice(a.length-l);a.unshift("...");""==e&&a.unshift(e)}return a};d.xm=function(a,b,l,e,c){e=d.um(a.protocol,a.hostname,a.port,e,c,b);l--;c=d.ob(a.search,b);l--;var h=d.ob(a.hash,b);l--;a=a.pathname.split("/");var k=
"";0<a.length&&(k=a.pop(),k=d.Eg(k,b),l--);a=d.vm(a,b,l);return 0==a.length?e+k+c+h:e+a.join("/")+"/"+k+c+h}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.Pc=function(){for(var l=0;l<d.Rd.length;l++)d.ja[d.Rd[l]]=d.aa.sh;for(l=0;l<d.Od.length;l++)d.ja[d.Od[l]]=d.aa.mh;d.ja.js=d.aa.gi;d.ja.css=d.aa.CSS;d.ja.svg=d.aa.ii;d.ja.html=d.aa.Qd;d.ja.htm=d.aa.Qd};d.Gc=function(d){return d.duration?d.duration:d.responseEnd&&d.startTime?d.responseEnd-d.startTime:
-1};d.Xe=function(l){var e;return(l=l.pathname)&&-1!=(e=l.lastIndexOf("."))?d.ja[l.substring(e+1,l.length).toLowerCase()]||d.aa.OTHER:d.aa.OTHER};return d}();a.aa={sh:"img",gi:"script",CSS:"css",ii:"svg",Qd:"html",mh:"font",OTHER:"other"};a.Rd="bmp gif jpeg jpg png webp".split(" ");a.Od=["ttf","woff","otf","eot"];a.ja={};d.Ta=a;a.Pc()})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(l){function e(d){c.marks.push(0==l[d]?-1:Math.round(l[d]-c.Mf))}this.marks=
[];var c=this;this.Mf=l.startTime;this.zk(l)?(this.Le=d.Ld,e("startTime"),e("fetchStart")):(this.Le=d.fe,e("startTime"),e("redirectStart"),e("redirectEnd"),e("fetchStart"),e("domainLookupStart"),e("domainLookupEnd"),e("connectStart"),e("secureConnectionStart"),e("connectEnd"),e("requestStart"),e("responseStart"));e("responseEnd")}d.Hj=function(){var l={};l[d.fe]=d.fi;l[d.Ld]=d.bh;return l};d.prototype.zk=function(d){return this.xa(d.redirectStart)&&this.xa(d.redirectEnd)&&(this.xa(d.domainLookupStart)||
this.xa(d.domainLookupEnd)||this.xa(d.connectStart)||this.xa(d.connectEnd))&&this.xa(d.secureConnectionStart)};d.prototype.xa=function(d){return!d||0===d};return d}();a.fe=1;a.Ld=2;a.fi="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd".split(" ");a.bh=["startTime","fetchStart","responseEnd"];d.ee=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}
d.prototype.Wb=function(d,e){if(d)return d.slice(0,e)};return d}();d.nh=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function b(){}b.prototype.Wb=function(b,e){if(b){if(b.length<=e)return b;for(var c=[],a=0;a<b.length;a++)c.push({jd:b[a],index:a});c.sort(function(e,c){return-(d.Ta.Gc(e.jd)-d.Ta.Gc(c.jd))});c=c.slice(0,e);c.sort(function(d,e){return d.index-e.index});for(var k=[],a=0;a<c.length;a++)k.push(c[a].jd);return k}};return b}();d.he=a})(d.events||(d.events=
{}))})(k||(k={}));(function(d){(function(d){var a=function(){function b(){}b.prototype.Wb=function(b,e){if(b){if(b.length<=e)return b;for(var c=1,a=Math.floor(Number.MAX_VALUE/4),k=b.length;c<a;){for(var m=b.length-1;0<=m;m--)if(d.Ta.Gc(b[m])<c&&(b.splice(m,1),k--),k<=e)return b;c*=4}return(new d.he).Wb(b,e)}};return b}();d.ei=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=d.utils.hasOwnPropertyDefined,b=function(){function e(c,b,a){this.version=2;this.resourceTimingInfo=
{};this.df={};this.ef={};this.dg={};this.eg={};this.kd=[];this.ti=function(e,c,b){if(e&&c&&0<c.length){this.sm=e;for(var a=new l,h=new l,k=0;k<c.length;k++){var f=c[k],m=d.utils.parseURI(d.utils.W.na(f.name)),v=f.initiatorType,B=g.Ta.Xe(m),C=new g.ee(f);this.kd.push({u:this.ym(m),i:a.Te(this.ef,v),r:h.Te(this.eg,B),f:C.Le,o:this.Aj(0===k&&f.isBase,C.Mf,e,b),m:C.marks,e:d.utils.isDefined(f.encodedBodySize)?f.encodedBodySize:-1,d:d.utils.isDefined(f.decodedBodySize)?f.decodedBodySize:-1,s:d.utils.isDefined(f.transferSize)?
f.transferSize:-1,p:d.utils.isDefined(f.nextHopProtocol)?f.nextHopProtocol:""})}}};var k=e.Bj();this.Ni(k,c);c=this.Vl(k,c);this.ti(b||d.monitor.navMonitor.navTiming&&d.monitor.navMonitor.navTiming.navigationStart,c,a);this.clearResourceTimings()}e.Pc=function(){var c=d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.sampler;e.Ul=c&&"FirstN"==c?new g.nh:c&&"TopN"==c?new g.he:new g.ei};e.prototype.bf=function(d,e){d[e]=d[e]?d[e]+1:1};e.prototype.ym=function(e){return d.utils.xm(e,
"number"===typeof d.conf.userConf.maxResUrlSegmentLength?d.conf.userConf.maxResUrlSegmentLength:d.conf.gh,"number"===typeof d.conf.userConf.maxResUrlSegmentNumber?d.conf.userConf.maxResUrlSegmentNumber:d.conf.hh,d.conf.Uh,d.conf.Th)};e.prototype.Ni=function(d,e){d&&this.cf(d);if(e&&0<e.length)for(var b=0;b<e.length;b++)this.cf(e[b])};e.prototype.cf=function(e){var b=d.utils.parseURI(d.utils.W.na(e.name)),b=g.Ta.Xe(b);this.bf(this.df,e.initiatorType);this.bf(this.dg,b)};e.prototype.Vl=function(c,b){if(b&&
0<b.length){var l=d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.maxNum||d.conf.Ph;c&&l--;b=e.Ul.Wb(b,l);c&&b.unshift(c)}return b};e.prototype.Aj=function(e,b,l,g){return e?1:d.utils.isDefined(g)?Math.round(b+l-g):Math.round(b)};e.prototype.build=function(){return 0==this.kd.length?null:{v:this.version,ic:this.df,it:this.ef,rc:this.dg,rt:this.eg,f:g.ee.Hj(),t:this.sm,r:this.kd}};e.Bj=function(){var e=d.monitor.navMonitor.navTiming,b=null;if(e){var b={},l;for(l in e)a(e,l)&&
(b[l]=e[l]);b.initiatorType="other";b.name=document.URL;b.navigationStart&&!b.startTime&&(b.startTime=b.navigationStart);b.isBase=!0}return b};e.prototype.clearResourceTimings=function(){d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.clearResTimingOnBeaconSend&&d.monitor.navMonitor.clearResourceTimings()};return e}();g.ResourceTimingInfoBuilder=b;var l=function(){function d(){this.il=1}d.prototype.Te=function(d,e){d[e]||(d[e]=this.il++);return d[e]};return d}();b.Pc()})(d.events||
(d.events={}))})(k||(k={}));(function(d){d.events||(d.events={})})(k||(k={}));(function(d){(function(g){var a=function(){function b(){}b.prototype.F=function(b,e){void 0===e&&(e={});var c={eventGUID:b.guid(),eventType:b.type(),eventUrl:d.utils.W.na(b.url()||document.URL),timestamp:d.utils.now()};b.type()!==d.EventType.PageView&&d.utils.mergeJSON(c,{parentGUID:b.parentGUID()||d.correlation.getPageGUID(),parentUrl:d.utils.W.na(b.parentUrl()||document.URL),parentType:b.parentType()||(d.utils.compareWindows(top,
window)?d.EventType.PageView:d.EventType.IFRAME)});var a=d.EventType[b.type()],a=g.ba.Yj(a,d.conf.userConf,e,d.conf.Ra),k;for(k in a)c[k]=a[k];return c};return b}();g.Oa=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=d.utils.isNumber,b=d.utils.isString,l=d.utils.isObject,e=d.utils.Be,c=d.utils.Sc,k=d.utils.isBoolean,f=function(){function c(){}c.Zc=function(e,c){var b=!1;if(l(e)){var g=d.utils.Ba(e);if(!g||g.length<=c)b=!0}return b};c.qd=function(d,e,l){if(b(e))if(e.length>
l)c.Ka(d,l,e.length);else return e;else c.Uc(d,"string")};c.Qb=function(d,e){return function(b,g,a){if(l(g)){var k,h;for(h in g)d(g[h])?(k=k||{},k[h]=g[h]):c.Uc(b,e,h);if(k){if(c.Zc(k,a))return k;c.Ka(b,a)}}else c.Uc(b,"object")}};c.Uc=function(d,c,b){e(d+" dropped because it was not a "+c+(b?", field name "+b:""))};c.Ka=function(d,c,b){e("User event info field "+d+" dropped because it is too long"+(b?" ("+b+" exceeds "+c+")":""))};return c}();f.Yj=function(e,c,b,g){if(c=c&&c.userEventInfo&&c.userEventInfo[e]){try{var a=
d.utils.isFunction(c)?c.call(null,b):c}catch(k){d.exception(k,"M213",e)}if(l(a))return f.Hm(a,g)}};f.Hm=function(d,e){var c={},b;for(b in f.Je)if(b in d){var l=f.Je[b](b,d[b],e);l&&(c[b]=l)}return c};f.rl=f.Qb(b,"string");f.ql=f.Qb(c,"integer");f.Jf=f.Qb(a,"number");f.pl=f.Qb(k,"boolean");f.Je={userPageName:f.qd,userData:f.rl,userDataLong:f.ql,userDataDouble:f.Jf,userDataBoolean:f.pl,userDataDate:f.Jf};g.ba=f})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=d.utils.isDefined,
b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}u(e,b);e.setPageName=function(d){e.oa=d};e.addUserData=function(d,b){e.pb=e.pb||{};e.pb[d]=b};e.prototype.F=function(c){var k=b.prototype.F.call(this,c||new g.PageView),f=this.Jj(),m=this.Cj();d.conf.viz&&(f&&d.utils.Ac(document.getElementById(d.conf.viz),f,"navtime"),d.utils.Ac(document.getElementById(d.conf.viz),m,"cookie"));m.PLC=1;f&&(f.PLC=1,f.VCT=d.utils.isDefined(c)?c.vct:0,f.PCT=d.utils.isDefined(c)?c.vct:0);d.monitor.ErrorMonitor.hadErrors&&
(m.EPM=1,f&&(f.EPM=1));d.utils.mergeJSON(k,{eventGUID:d.correlation.getPageGUID(),eventType:d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME,cookieMetrics:m});c=-1;f&&f.timestamp?c=f.timestamp:m&&m.timestamp&&(c=m.timestamp);0<c&&d.utils.mergeJSON(k,{timestamp:c});f&&(k.metrics=f);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(k.pageReferrer=d.utils.W.na(document.referrer));f=e.Mj();0<f.length&&(k.pageTitle=f);f=d.correlation.Ze();null!==f&&(k.serverMetadata=
f);f=0<d.monitor.resourceMonitor.basePageResourceBuffer.length?(new g.ResourceTimingInfoBuilder(d.monitor.resourceMonitor.basePageResourceBuffer)).build():null;null!==f&&(k.resourceTimingInfo=f);!a(k.userData)&&a(e.pb)&&(g.ba.Zc(e.pb,d.conf.Ra)?k.userData=e.pb:g.ba.Ka("userData",d.conf.Ra));!a(k.userPageName)&&a(e.oa)&&(g.ba.qd("userPageName",e.oa,d.conf.Sa)?k.userPageName=e.oa:g.ba.Ka("userPageName",d.conf.Sa));e.userPageName=k.userPageName;return k};e.prototype.Jj=function(){if(!d.monitor.navMonitor.navTiming)return null;
var b={},l=e.Ve(d.monitor.navMonitor.navTiming,b,"NT"),a=g.metricSpec[d.EventType.PageView],k;for(k in a){var p=a[k];l.add(p.name,p.start,p.end)}b.timestamp=d.monitor.navMonitor.navTiming.navigationStart;return b};e.prototype.Cj=function(){var b={};d.commands.marks&&(e.Ve(d.commands.marks,b,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready"),b.timestamp=
d.commands.marks.starttime?d.commands.marks.starttime:d.commands.marks.firstbyte);return b};e.Mj=function(){var e=d.conf.userConf,e=e&&e.page,b;b=e&&"captureTitle"in e?e.captureTitle:!0;var l,g;e&&(l="title"in e,g=e.title);l=b?l?d.utils.isFunction(g)?g():g:document.title:"";if(d.utils.isString(l))return l;d.utils.Be("Ignoring wrong type of page title: "+typeof l);return""};e.ri=function(e,b,l,g,a,k){b=g[b];l=g[l];b&&l?a[e]=l-b:d.log("M214",k,e,b,l)};e.Ve=function(d,b,l){var g={add:function(a,k,t){e.ri(a,
k,t,d,b,l);return g}};return g};return e}(g.Oa);g.ka=b})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){(function(g){function b(c,g){var a,m=g[c],q=typeof m;r.push(c);var C=n[r.join(".")];if(d.utils.isFunction(C))a=C(m);else switch(q){case "string":a="number"==typeof C?p(m,e,C):e(m);break;case "number":a=f(m);break;case "object":if(m)if(d.utils.isArray(m))a=k(m,!1,!1);else{a=[];for(var z in m)t(m,z)&&(q=b(z,m))&&(l(c)&&"timestamp"==z||a.push({Lb:z,v:q}));if(l(c)){for(m=0;m<a.length;m++)a[m]=
a[m].Lb+e(":")+a[m].v;a=e("{")+a.join(e(","))+e("}")}else{for(m=0;m<a.length;m++)z=a[m],q=z.Lb,d.conf.useDebugBeaconParams||((C=d.conf.zf[z.Lb])?q=C:d.error("M215",z.Lb)),a[m]=q+"="+z.v;a=a.join("&")}}else a=null}r.pop();return a}function l(d){return"navOrXhrMetrics"==d||"cookieMetrics"==d}function e(d){return"undefined"===typeof d||null===d||0===d.length?null:encodeURIComponent(d)}function c(d){return encodeURIComponent(encodeURIComponent(d))}function k(d,c,g){void 0===c&&(c=!1);void 0===g&&(g=!0);
if(0===d.length)return null;var l=[];if(c)l=d;else for(c=0;c<d.length;c++)l.push(b(c,d));return e("[")+l.join(e(","))+e(g?">":"]")}function f(d){d=Math.round(d);d<g.ce&&(d=g.ce);d>g.$d&&(d=g.$d);return e(d)}function m(d,b){if(d>b||0>d)d=g.Zh;return e(d)}function p(e,b,c,g){void 0===g&&(g=!0);if("undefined"===typeof e||null===e||0===e.length)return null;var l=3<=c?"...":"";d.assert(c>=l.length);for(var a=!1,k=null;;){try{k=b(e);if(null===k)return null;if(k.length<=c)break}catch(h){}var f;a?f=e.length-
1:(a=!0,f=c-=l.length);var m=g?0:Math.max(e.length-f,0);e=e.substr(m,f)}a&&(k=g?k+l:l+k);return k}function q(e,b,c){if(0==c)return g.hc;if(b<e)return 0;b=g.hc+(b-e)/c;d.assert(b>=g.hc);d.log("M216",e,b);return b}var t=d.utils.hasOwnPropertyDefined;g.Zh=-1;g.Qa=180;g.Rh=50;g.Sh=50;g.Lh=40;g.hc=50;g.zh=50;g.be=128;g.Gh=30;g.Hh=30;g.Fh=30;g.Nh=8;g.ce=-99999;g.$d=999999;g.Ah=2E3;g.Qh=2;g.Bh=99999999;var n={".pageUrl":g.Qa,".parentPageUrl":g.Qa,".pageReferrer":g.Qa,".pageTitle":g.Rh,".userPageName":g.Sh,
".geoCountry":g.Gh,".geoRegion":g.Hh,".geoCity":g.Fh,".localIP":g.Nh,".otherClientRequestGUIDs":function(d){d=d||[];var e=d.slice(0,g.Qh);return k(e,!1,e.length<d.length)},".btTime":function(e){e=e||[];for(var b=e.slice(0,d.conf.Ch),c=[],l=0;l<b.length;l++){var p=b[l];c.push(k([m(Number(p[0]),g.Bh),f(p[1]),f(p[2])],!0,!1))}return k(c,!0,b.length<e.length)},".ajaxError":function(d){return k([c(d[0]),p(d[1],c,g.zh)],!0,!1)},".userData":function(d){d=d||[];for(var e=!1,b=0,l=[],f=0;f<d.length;f++){var m=
d[f];l[f]=k([c(m[0]),c(m[1])],!0,!1);b+=l[f].length;if(b>g.be){e=!0;break}}for(;;){d=k(l,!0,e);if(null===d||d.length<=g.be)return d;l.pop();e=!0}}},r=[];g.hj=function(e,l){void 0===l&&(l=!0);r=[];var m=[];e.errors&&(m=e.errors,e.errors=null);var n=b("",{"":e});if(m&&0<m.length){for(var t=q(l?870:354,g.Ah-n.length,m.length),C=[],z=0;z<m.length;z++){var u=m[z],A=d.utils.W.Ie(d.utils.W.na(u[0]));C.push(k([p(A,c,g.Lh,!1),d.utils.Sc(u[1])?f(u[1]):-1,p(u[2],c,t)],!0,!1))}m=k(C,!0,!1);n+="&errors="+m}return n};
g.yn=b;g.Yn=e;g.element=c;g.qn=k;g.tn=f;g.Nn=m;g.truncate=p;g.Un=q})(g.Xd||(g.Xd={}))})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(g){var a=d.utils.hasOwnPropertyDefined,b=d.utils.Ab,l=function(){function e(){}e.prototype.Nb=function(b,l,a){for(var k=[],p=[],q=null,t=[],n=0;n<b.length;n++){var r=b[n];if(r.eventType===d.EventType.Error){var u=r;p.push([r.eventUrl+"",d.utils.Sc(u.line)?u.line:void 0,u.message+""])}else{if(r.eventType===d.EventType.PageView||r.eventType===d.EventType.IFRAME)q=
r;t.push(r)}}b=t;if(0<p.length)for(q&&(q.errors=p.splice(0,d.conf.Jh));0<p.length;)r=p.splice(0,d.conf.Ih),q=e.ul.F(),q.errors=r,q.isErrorEvent=!0,q.cookieMetrics=null,q.metrics=null,q.resourceTimingInfo=null,b.push(q);for(p=0;p<b.length;p++)r=b[p],d.log("M217"),r.resourceTimingInfo=null,e.uj(r,l,a),q=e.transform(r),k.push(g.Xd.hj(q,r.isErrorEvent));return k};e.uj=function(e,b,g){e.ver=this.th;e.rootGUID=g.Ic();e.geo=b;e.dataType="R";e.eom=1;e.eumAppKey=d.conf.appKey;e.PLC=1};e.transform=function(d){var b=
{};e.Lg("",{"":d},b);return b};e.Lg=function(c,g,l){g=g[c];var k=e.wf[c];if("metrics"===c||"cookieMetrics"===c)l[k]=g;else if("btTime"===c&&d.utils.isArray(g)&&0<g.length){c=[];for(var p=0;p<g.length;p++)c.push([g[p].id,g[p].duration,g[p].ert]);l[k]=c}else if("userData"===c&&d.utils.isObject(g))l[k]=d.utils.dl(g);else if(!(c&&-1<b(["userDataLong","userDataDouble","userDataBoolean","userDataDate"],c)))if(d.utils.isObject(g))for(p in g)a(g,p)&&e.Lg(p,g,l);else e.wf[c]&&("eventType"===c&&g>d.EventType.Ajax&&
(g=d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME),l[k]=g)};return e}();l.ul=new d.events.ka;l.th=3;l.wf={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",
cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};g.xh=l})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.send=
function(){};return d}();d.lh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.Nb=function(){return null};return d}();d.kh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(d){this.Zk=d}b.prototype.send=function(b){try{this.Zk.postMessage(d.utils.Ba(b)),d.log("M218"),g.numBeaconsSent+=1}catch(e){d.log("M219")}};return b}();g.qh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(g){var a=
function(){function b(){}b.prototype.Nb=function(b,e,c){b={ver:d.conf.agentVer,dataType:"R",rootGUID:c.Ic(),events:b};d.channel.V.T&&d.channel.V.T.id&&(b.agentId=d.channel.V.T.id);e&&(b.geo=e);return b};return b}();g.ph=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){var g=function(){function g(){}g.Ae=function(b,g){if(!b)return null;var e=b.ADRUM.lifecycle;if(!e||!e.getPhaseCallbackTime)return null;var c=g.getPhaseCallbackTime("AT_ONLOAD"),e=e.getPhaseCallbackTime("AT_ONLOAD"),a=null==e;
return null==c?(d.error("M220"),null):d.lifecycle.getPhaseID(a||c<=e?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return g}();d.bi=g;d.cPLPI=g.Ae})(k||(k={}));(function(d){(function(g){var a=function(){function b(b){this.ready=!1;this.geoResolverUrl=b;d.utils.isString(b)&&0<d.utils.trim(b).length&&(this.geoResolverUrl=b+"/resolve.js")}b.prototype.init=function(b){this.channel=b;if(this.wc()&&(d.geo=this.vd(),this.Ai()||this.Sb()&&!this.Ne())){this.channel.ld(d.geo.result);return}this.Ne()?(this.Sb()&&(this.geoResolverUrl+=
"?ip="+encodeURIComponent(d.conf.userConf.geo.localIP)),this.Em()):(this.ready=!0,this.channel.onResolverReady())};b.prototype.wc=function(){return d.utils.isDefined(d.conf.userConf)&&d.utils.isDefined(d.conf.userConf.geo)};b.prototype.Sb=function(){return this.wc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&!d.utils.isDefined(d.conf.userConf.geo.city)&&!d.utils.isDefined(d.conf.userConf.geo.region)&&!d.utils.isDefined(d.conf.userConf.geo.country)};b.prototype.vd=function(){return{failed:!1,
result:{country:d.conf.userConf.geo.country,region:d.conf.userConf.geo.region,city:d.conf.userConf.geo.city,localIP:this.jj(d.conf.userConf.geo.localIP)}}};b.prototype.Ai=function(){return this.wc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&d.utils.isDefined(d.conf.userConf.geo.city)&&d.utils.isDefined(d.conf.userConf.geo.region)&&d.utils.isDefined(d.conf.userConf.geo.country)};b.prototype.Ne=function(){return d.utils.isString(this.geoResolverUrl)&&0<d.utils.trim(this.geoResolverUrl).length};
b.prototype.jj=function(d){if(null==d||0==d.length)return null;d=d.split(".");if(4!=d.length)return null;for(var e=[],b=0;b<d.length;b++){var g=parseInt(d[b]);if(isNaN(g)||0>g||255<g)return null;e.push(("0"+g.toString(16)).slice(-2))}return e.join("")};b.prototype.Em=function(){d.geo={failed:!1,result:null};d.utils.loadScriptAsync(this.geoResolverUrl);var g=this;d.utils.tryPeriodically(b.qc,function(){return g.isReady()},function(){g.onReady()},function(){g.$c()})};b.prototype.isReady=function(){this.ready||
(this.ready=d.geo&&(d.geo.failed||null!==d.geo.result))||d.log("M221");return this.ready};b.prototype.onReady=function(){d.geo.failed?(d.log("M222"),this.Sb()&&(d.geo=this.vd())):(d.assert("object"===typeof d.geo.result),d.log("M223",d.geo.result));d.geo&&d.geo.result&&this.channel.ld(d.geo.result);this.channel.onResolverReady()};b.prototype.$c=function(){d.log("M224");this.Sb()&&(d.geo=this.vd());d.geo&&d.geo.result&&this.channel.ld(d.geo.result);this.ready=!0;this.channel.onResolverReady()};b.qc=
function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return b}();g.oh=a})(d.channel||(d.channel={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(){this.ready=!1;this.channel=null}b.prototype.init=function(g){this.channel=g;b.Y=b.Y||b.xj();this.ready=!b.Y.Ib;var e=this;if(b.Y.Ib)d.log("M225"),b.Y.Ib.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){d.log("M226");e.ready=!0;e.onReady()});else e.onReady()};b.prototype.isReady=function(){this.isReady||d.log("M227");
return this.ready};b.prototype.onReady=function(){this.channel.$l(b.Y);this.channel.onResolverReady()};b.xj=function(){for(var g=window,e,c=b.uf(g),a=window;a.parent&&!d.utils.compareWindows(a,a.parent);){a=a.parent;c=c||b.uf(a);try{a.ADRUM&&(e=e||a,g=a)}catch(k){}}return new d.Xg(e,g,c)};b.uf=function(d){try{return 0==d.document.URL.indexOf("https:")}catch(e){}};return b}();a.Y=null;g.Yg=a})(d.channel||(d.channel={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(e,c,l){this.events=
[];this.ua={};this.Db=NaN;this.ma=[];this.Fc=!1;this.bufferMode=d.conf.userConf&&d.conf.userConf.channel&&"undefined"!==typeof d.conf.userConf.channel.bufferMode?d.conf.userConf.channel.bufferMode:!0;this.Xb=-1;this.tm=e;this.Hi=c;this.ma.push(new g.oh(l));this.ma.push(new g.Yg);this.ma.push(new g.V)}b.create=function(){var e,c;e=b.zl();d.utils.isDefined(e)?(e=new d.beacons.qh(e),c=new d.beacons.ph):d.utils.isCORSSupported()&&!d.conf.sendImageBeacon?(e=new d.beacons.ah,c=new d.beacons.$g):d.conf.neverSendImageBeacon?
(e=new d.beacons.lh,c=new d.beacons.kh):(e=new d.beacons.yh,c=new d.beacons.xh);e=new b(e,c,d.conf.geoResolverUrl);e.init();return e};b.prototype.init=function(){for(var d=0;d<this.ma.length;d++)this.ma[d].init(this)};b.prototype.Mm=function(b){return(b.parentType===d.EventType.VPageView||b.parentType===d.EventType.NG_VIRTUAL_PAGE)&&null!==this.ua[b.parentGUID]};b.prototype.ed=function(b){var c=b.parentGUID;if(!d.utils.isDefined(this.ua[c])){this.ua[c]=[];var g=this,l=b.eventGUID;d.utils.oSTO(function(){g.zc(l)},
1E4)}this.ua[c].push(b)};b.prototype.report=function(e){e.sequenceId=d.og.ye.Fj();e.timestamp=e.timestamp||d.utils.now();this.Mm(e)?this.ed(e):this.events.push(e);1==this.events.length&&(this.Db=d.utils.now());var c=e.parentGUID;c&&c!==d.correlation.getPageGUID()||this.zc(e.eventGUID);b.Ek(e)&&(this.Fc=!0);this.td()};b.prototype.zc=function(d){var b=this.ua[d];this.ua[d]=null;if(b&&0!=b.length)for(this.events=this.events.concat(b),d=0;d<b.length;d++)this.zc(b[d].eventGUID)};b.prototype.Kk=function(b){return b.eventType===
d.EventType.PageView||b.eventType===d.EventType.IFRAME};b.prototype.Ii=function(){for(var b=0;b<this.events.length;b++){var c=this.events[b];if(this.Kk(c)){var g=this.Y.Ib;g&&(c.parentLifecyclePhase=d.bi.Ae(g,d.lifecycle),c.parentGUID=g.ADRUM.correlation.getPageGUID(),c.parentUrl=d.utils.W.na(g.document.URL),d.utils.isDefined(g.ADRUM.events.ka.userPageName)&&(c.vl=g.ADRUM.events.ka.userPageName),c.parentType=d.utils.compareWindows(top,g)?d.EventType.PageView:d.EventType.IFRAME)}}};b.prototype.Xl=
function(){if(0==this.events.length)d.log("M228");else{this.Ii();var b=this.wd(this.events,this.Y),c=this.Hi.Nb(this.events,this.wj,this.Y);this.tm.send(c,b);this.events=[];this.Db=Number.POSITIVE_INFINITY}};b.prototype.onResolverReady=function(){this.td()};b.prototype.ld=function(d){this.wj=d};b.prototype.$l=function(d){this.Y=d};b.prototype.addResolver=function(d){d.init(this);this.ma.push(d)};b.prototype.Rl=function(){for(var d=0;d<this.ma.length;d++)if(!this.ma[d].isReady())return!1;return!0};
b.prototype.vf=function(){return this.Db+d.conf.Zd>d.utils.now()};b.prototype.Rk=function(){return this.events.length<d.conf.Dh};b.prototype.wd=function(b,c){if(c.wd||d.conf.userConf.useHTTPSAlways)return!0;for(var g=0;g<b.length;g++){var l=b[g];if(l.eventUrl&&0==l.eventUrl.indexOf("https:"))return!0}return!1};b.prototype.getEventsWithParentGUID=function(d){return this.ua[d]||[]};b.prototype.td=function(){if(this.Rl())if(this.Lm()){if(this.vf()&&0<this.events.length&&0>this.Xb){var b=this;this.Xb=
d.utils.oSTO(function(){b.td()},d.conf.Zd+this.Db-d.utils.now())}}else clearTimeout(this.Xb),this.Xb=-1,this.Fc=!1,this.Xl()};b.Ek=function(b){return b.eventType===d.EventType.PageView||b.eventType===d.EventType.IFRAME||b.eventType===d.EventType.VPageView};b.prototype.Lm=function(){return this.bufferMode&&!this.Fc&&this.Rk()&&this.vf()};b.Al=function(){if(d.utils.isDefined(window.webkit)&&d.utils.isDefined(window.webkit.messageHandlers)&&d.utils.isDefined(window.webkit.messageHandlers.ADEUM_js_handler)&&
d.utils.isFunction(window.webkit.messageHandlers.ADEUM_js_handler.postMessage))return window.webkit.messageHandlers.ADEUM_js_handler};b.yl=function(){if(d.utils.isDefined(window.ADEUM_js_handler)&&d.utils.isFunction(window.ADEUM_js_handler.postMessage))return window.ADEUM_js_handler};b.zl=function(){return b.yl()||b.Al()};return b}();g.Channel=a;var b=a.create();g.report=function(d){b.report(d)};g.addResolver=function(d){b.addResolver(d)};g.getEventsWithParentGUID=function(d){return b.getEventsWithParentGUID(d)}})(d.channel||
(d.channel={}))})(k||(k={}));(function(d){var g=function(){function g(){}g.Uf=function(){return window.attachEvent?d.utils.isFunction(window.addEventListener)?this.yd:this.Bg:this.Gg};g.Tf=function(b){var l=null;switch(g.Uf()){case g.Gg:l=b.parentPhase();break;case g.yd:l=d.lifecycle.findPhaseAtNominalTime(b.getSendTime());break;case g.Bg:l=null}return d.lifecycle.getPhaseID(l)};return g}();g.Gg="uCT";g.yd="uNET";g.Bg="tIA";d.xb=g})(k||(k={}));(function(d){(function(g){var a=d.utils.hasOwnPropertyDefined,
b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}u(e,b);e.prototype.F=function(c){var a=b.prototype.F.call(this,c,e.getContext(c)),k=c.url(),m=c.getSendTime(),p=c.getFirstByteTime(),q=c.getRespAvailTime(),t=c.getRespProcTime(),n=c.parentPhase();d.assert(null!==k&&null!==m&&null!==p&&null!==q&&null!==t,"M229",k,m,p,q,t,n);if(null===k||null===m||null===p||null===q||null===t)return null;k=c.error();m={PLC:1,FBT:p-m,DDT:q-p,DPT:t-q,PLT:t-m,ARE:k?1:0};p=c.url();if(!e.Yk(m,p))return null;
d.conf.viz&&d.utils.Ac(document.getElementById(d.conf.viz),m,"xhr");d.utils.mergeJSON(a,{eventUrl:d.utils.W.na(p),parentLifecyclePhase:c.parentPhaseId(),metrics:m,method:c.method(),timestamp:c.timestamp(),ajaxError:k&&[k.status,k.msg||""],xhrStatus:c.xhrStatus()});(c=c.parameter())&&g.ba.Zc(c,d.conf.Ra)?a.parameter=c:c&&g.ba.Ka("parameter",d.conf.Ra);a.parentType==d.EventType.VPageView&&d.conf.spa2?d.utils.pg(a,g.tb.userPageName):d.utils.pg(a,g.ka.userPageName);return a};e.getData=function(b){if(d.utils.isDefined(b)&&
d.utils.isDefined(b.data))return b.data};e.getContext=function(d){return{url:d.url()||"",method:d.method()||"",data:e.getData(d.dataObject())||""}};e.Yk=function(b,e){for(var g in b)if(a(b,g)){var l=b[g];if(0>l)return d.error("M230",g,l,e),!1}return!0};return e}(g.Oa);g.je=b})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=function(b){function g(){return null!==b&&b.apply(this,arguments)||this}u(g,b);g.prototype.F=function(e){var g=b.prototype.F.call(this,e);g&&(e=e.allResponseHeaders()||
"",(e=d.correlation.Vj(e))&&null!==e&&null!==e.clientRequestGUID&&(g.eventGUID=e.clientRequestGUID),null!==e&&(g.serverMetadata=e));return g};return g}(g.je);g.Sg=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=function(b){function l(){return null!==b&&b.apply(this,arguments)||this}u(l,b);l.prototype.F=function(e){var c=b.prototype.F.call(this,e);d.utils.mergeJSON(c,{message:e.msg()||"",timestamp:e.timestamp(),line:e.line(),stack:e.stack(),parentPageName:c.parentType==d.EventType.VPageView&&
d.conf.spa2?g.tb.userPageName:g.ka.userPageName});d.utils.isString(c.userPageName)||(c.userPageName=c.vl);return c};return l}(g.Oa);g.ai=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){(function(a){a.build=function(b){var l={},e=d.metricSpec[b.type()],c;for(c in e){var a=e[c];if(null!==a.name&&b.perf.getEntryByName(a.start)&&b.perf.getEntryByName(a.end)){b.perf.measure(a.name,a.start,a.end);var k=b.perf.getEntryByName(a.name);l[a.name]=k&&0<=k.duration&&k.duration||null}}for(c in l)l[c]=
Math.round(l[c]);return l}})(d.jc||(d.jc={}))})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(b){function a(){return null!==b&&b.apply(this,arguments)||this}u(a,b);a.prototype.F=function(e){var c=b.prototype.F.call(this,e),a=d.jc.build(e);a.PLC=1;c.metrics=a;c.timestamp=e.timestamp();e=(new d.ResourceTimingInfoBuilder(e.resTiming())).build();null!==e&&(c.resourceTimingInfo=e);return c};return a}(d.Oa);d.ie=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(g){var a=
function(b){function a(){return null!==b&&b.apply(this,arguments)||this}u(a,b);a.setPageName=function(d){a.oa=d};a.prototype.F=function(e){var c=b.prototype.F.call(this,e),k=g.jc.build(e);k.PLT=e.timestamp()-e.startTime;k.VCT=e.vct;k.PLC=1;c.metrics=k;c.timestamp=e.timestamp();k=(new g.ResourceTimingInfoBuilder(e.resTiming(),null,e.startTime)).build();null!==k&&(c.resourceTimingInfo=k);d.utils.isDefined(e.userPageName)&&(c.userPageName=e.userPageName);!d.utils.isDefined(c.userPageName)&&d.utils.isDefined(a.oa)&&
(g.ba.qd("userPageName",a.oa,d.conf.Sa)?c.userPageName=a.oa:g.ba.Ka("userPageName",d.conf.Sa),a.oa=void 0);return c};return a}(g.Oa);g.tb=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(d){function g(){return null!==d&&d.apply(this,arguments)||this}u(g,d);g.prototype.F=function(e){var g=d.prototype.F.call(this,e);g&&(g.metrics.VDC=e.digestCount()||0);return g};return g}(d.ie);d.Yh=a})(d.events||(d.events={}))})(k||(k={}));(function(d){var g=d.events||(d.events={});
g.ag={};d=[{Ca:g.PageView,ya:new g.ka},{Ca:g.Ajax,ya:new g.je},{Ca:g.AdrumAjax,ya:new g.Sg},{Ca:g.Error,ya:new g.ai},{Ca:g.VPageView,ya:new g.ie},{Ca:g.AnySpaVPageView,ya:new g.tb},{Ca:d.ng.NgVPageView,ya:new g.Yh}];for(var a=0;a<d.length;a++){var b=d[a];b.Ca.prototype._regId=a;g.ag[a]=b.ya}})(k||(k={}));(function(d){(function(g){g.reportEvent=function(g){var b=d.events.ag[g._regId];b?(b=b.F(g),d.utils.isDefined(b)&&(d.log("M232",d.EventType[g.type()]),d.channel.report(b))):d.log("M231",d.EventType[d.eventType])}})(d.reporter||
(d.reporter={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(){this.ready=!1}b.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};b.prototype.isReady=function(){this.ready||d.log("M233");return this.ready};b.prototype.init=function(d){this.channel=d};return b}();g.oi=a})(d.commands||(d.commands={}))})(k||(k={}));(function(d){(function(g){var a=new g.oi;d.channel.addResolver(a);g.marks={};g.mark=function(b,a){d.log("M234",b,a);g.marks[b]=a};g.reportOnload=
function(b){d.utils.oSTO(function(){d.log("M235");d.reporter.reportEvent(b);a.onReady()},d.conf.mi)};g.reportEvent=function(){d.reporter.reportEvent.apply(d.reporter,arguments)};g.addResolver=function(b){d.channel.addResolver(b)};g.reportXhr=function(b){d.log("M236");d.xb.Uf()==d.xb.yd?(d.log("M237"),d.utils.oSTO(function(){b.parentPhaseId(d.xb.Tf(b));d.reporter.reportEvent(b)},0)):(b.parentPhaseId(d.xb.Tf(b)),d.reporter.reportEvent(b))};g.listenForOkToSendChildFrameBeacons=function(b){d.log("M238");
try{b()}catch(g){d.exception(g,"M239")}};g.reportPageError=function(b){var g=b.url();d.log("M240",b.msg(),g,b.line(),b.stack());g&&0!==g.length||b.url("CROSSORIGIN");d.reporter.reportEvent(b)};g.setPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.events.ka.setPageName(b)};g.setVirtualPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.conf.spa2&&d.events.tb.setPageName(b)};g.addUserData=function(b,g){d.events.ka.addUserData(b,g)};g.call=function(d){d()}})(d.commands||
(d.commands={}))})(k||(k={}));(function(d){(function(d){d.He=function(a){return encodeURIComponent(d.W.ol(a))}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(g){var a=function(){function b(){}b.prototype.setUp=function(){this.fl();d.utils.addEventListener(window,"pagehide",b.Ed);d.utils.addEventListener(window,"beforeunload",b.Ed);d.utils.addEventListener(window,"unload",b.Ed)};b.prototype.fl=function(){(this.startTime=b.sj()||b.rj())&&d.commands.mark("starttime",this.startTime)};b.sj=
function(){var b;try{if(d.utils.isDefined(window.external)&&d.utils.isNumber(window.external.pageT))b=(new Date).getTime()-window.external.pageT;else if(d.utils.isDefined(window.gtbExternal)&&d.utils.isFunction(window.gtbExternal.pageT)){var e=window.gtbExternal.pageT();d.utils.isNumber(e)&&(b=(new Date).getTime()-e)}else d.utils.isDefined(window.chrome)&&d.utils.isFunction(window.chrome.csi)&&(e=window.chrome.csi(),d.utils.isDefined(e)&&d.utils.isNumber(e.pageT)&&(b=(new Date).getTime()-e.pageT));
b&&(b=Math.round(b),d.log("M241",b))}catch(g){d.exception(g,"M242")}return b};b.rj=function(){var b=d.correlation.startTimeCookie;if(b){d.log("M243",b.startTime,b.startPage);var e=d.utils.He(document.referrer);if(e===b.startPage)if(isNaN(b.startTime))d.log("M244",b.startTime);else return b.startTime;else d.log("M245",e,b.startPage)}else d.log("M246")};b.fj=function(b,e){var g=document.domain,a="https:"===document.location.protocol,k="ADRUM=s="+Number(new Date)+"&r="+d.utils.He(document.location.href),
m=k+";path=/";a&&(m+=";secure");d.log("M247",k);if(!d.conf.useStrictDomainCookies){for(var a=b(),g=g.split("."),p="",q=g.length-1;0<=q;q--){p="."+g[q]+p;d.log("M248",p);e(m+";domain="+p);var t=b();if(t!=a&&0<=t.indexOf(k)){d.log("M249");d.log("M250");return}}d.log("M251")}d.log("M252");e(m);d.log("M253")};return b}();a.Ed=function(){var d=!1;return function(){d||(d=!0,a.fj(function(){return document.cookie},function(d){document.cookie=d}))}}();g.en=a;g.mm=new a})(d.monitor||(d.monitor={}))})(k||(k=
{}));(function(d){d.log("M254");d.monitor.mm.setUp();d.q.processQ();d.initEXTDone=!0;d.log("M255")})(k||(k={}))}};})();
